#:schema node_modules/wrangler/config-schema.json
name = "opennext-cf"
main = ".open-next/worker.js"

compatibility_date = "2024-12-20"
compatibility_flags = ["nodejs_compat"]

# Assets used for files and cache priming.
assets = { directory = ".open-next/assets", binding = "ASSETS" }

# replace with your settings
[[d1_databases]]
binding = "DB"
database_name = "opennext-cf"
database_id = "6f935ec4-8a5c-4f21-a9d6-519dc216317a"
